export enum NotificationType {
  NEW_REQUEST = 'NEW_REQUEST',
  REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
  VENDOR_EN_ROUTE = 'VENDOR_EN_ROUTE',
  VENDOR_ARRIVED = 'VENDOR_ARRIVED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  ADDITIONAL_SERVICE_RECOMMENDED = 'ADDITIONAL_SERVICE_RECOMMENDED',
  ADDITIONAL_SERVICE_APPROVED = 'ADDITIONAL_SERVICE_APPROVED',
  SCHEDULE_CHANGED = 'SCHEDULE_CHANGED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  NEW_MESSAGE = 'NEW_MESSAGE',
}
