export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  VENDOR = 'VENDOR',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  SUSPENDED = 'SUSPENDED',
}

export enum ServiceRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  VENDOR_EN_ROUTE = 'VENDOR_EN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PlanTier {
  BASIC = 'BASIC',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum NoteType {
  OBSERVATION = 'OBSERVATION',
  FINDING = 'FINDING',
}

export enum DisputeCategory {
  WORK_NOT_COMPLETED = 'WORK_NOT_COMPLETED',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  WRONG_PRICE = 'WRONG_PRICE',
  SERVICE_NOT_AS_DESCRIBED = 'SERVICE_NOT_AS_DESCRIBED',
  OTHER = 'OTHER',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED_CUSTOMER = 'RESOLVED_CUSTOMER',
  RESOLVED_VENDOR = 'RESOLVED_VENDOR',
}
